apiVersion: v1
kind: Pod
metadata:
  name: nodejs-web 
  labels:
    name: nodejs-web
spec:
  volumes:
    - name: volume-name               #volume-name
      emptyDir: {}
  containers:
    - name: nodejs-web                #container-name
      image: khannedy/nodejs-web      #image-name
      ports: 
        - containerPort: 80
      resources:
        requests:
          cpu: 1000m                  #1000m = 1000 millicore = 1 core 
          memory: 250Mi               #250mi = 250 mebibyte = mirip dengan 250 MB
        limits:
          cpu: 2000m                  #2000m = 2000 millicore = 2 core 
          memory: 500Mi               #500mi = 500 mebibyte = mirip dengan 500 MB