apiVersion: v1
kind: Pod
metadata: 
  name: nodejs-writer                        #pod-name
  labels:
    name: nodejs-writer
spec:
  volumes:
    - name: html                             #volume-name
      emptyDir: {}
  containers: 
    - name: nodejs-writer                    #container-name
      image: khannedy/nodejs-writer          #image-name
      #ports:
        #- containerports: 80
      volumeMounts: 
        - mountPath: /app/html
          name: html      
