
##membuat HPA
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: 
  name: hpa-name                                     #hpa-name
spec:
  minReplicas: 3                                     #jika pada saat deployment men-setting replicas=5, namun minReplicas = 3, maka pod yang akan dibuat tetap akan mengikuti minReplicas HPA yakni 3 pod saja 
  maxReplicas: 5                                     #maksimal pod yang ditambahkan adalah menjadi total 5 pod, bukan ditambahkan 5 pod
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodejs-web                                 #deployment-name     #menargetkan ke nama deployment yang akan/telah dibuat
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: 
          type: Utilization
          averageUtilization: 70                      #jika rata-rata penggunaannya cpunya melebihi 70%, maka pod baru akan dibuat secara otomatis
    - type: Resource
      resource:
        name: memory                                  #pastikan bahasa pemrograman yang digunakan dapat me-manage memori dengan baik. Contohnya jika menggunakan java, memory-nya tidak akan pernah bisa turun.
        target: 
          type: Utilization
          averageUtilization: 70                      #jika rata-rata penggunaannya RAM melebihi 70%, maka pod baru akan dibuat secara otomatis