apiVersion: v1
kind: Pod
metadata: 
  name: nodejs-writer                          #pod-name
  labels:
    name: nodejs-writer
spec:
  volumes: 
    - name: html
      emptyDir: {}
  containers: 
    - name: nodejs-writer                       #container-name
      image: khannedy/nodejs-writer             #image-name
      volumeMounts:
        - mountPath: /app/folder-from-env
          name: html
      #ports:
        #- containerPort: 80
      env: 
        - name: HTML_LOCATION                    #ENV_NAME
          value: /app/folder-from-env            #ENV_VALUE