##membuat pod
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: nginx
spec: 
  replicas: 3
  selector: 
    matchLabels:
      name: nginx                #pastikan matchLabels HARUS SAMA dengan label-template
  template: 
    metadata: 
      name: nginx
      labels: 
        name: nginx              #label-template (label pod) haru sama dengan matchLabels dan label service
    spec: 
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80

---

##membuat service
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec: 
  type: LoadBalancer
  selector: 
    name: nginx
  ports:
    - port: 80                      #port yang digunakan oleh cluster lain (dalam satu server kubernetes) untuk mengakses aplikasi tersebut
      targetPort: 80                #port aplikasi yang ada di server
