apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-annotation  #pod-name
  labels: 
    team: product
  annotations:
    description: Ini adalah aplikasi yang dibuat oleh tim product.
    apapun: Apapun itu....
spec:
  containers:
    - name: nginx                   #container-name
      image: nginx              #image-name
      ports:
         - containerPort: 80