##membuat persistent volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nodejs-writer-volume                  #persistent-volume-name
spec: 
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:                                   #bisa diganti dengan persistent volume dari provider cloud lain
    path: /data/location

---

##membuat persistenr volume claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodejs-writer-volume-claim             #persistent-volume-claim-name
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi 
