apiVersion: v1
kind: Pod
metadata:
  name: nginx                   #pod-name
spec:
  containers:
    - name: nginx               #container-name
      image: nginx              #image-name
      ports:
        - containerPort: 80
        
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80

