apiVersion: v1
kind: Service
metadata:
  name: external-service         #service-name harus sama dengan endpoint-name
  labels:
    label1: label
spec: 
  ports:
    - port: 80

---

##harus membuat object Endpoints
apiVersion: v1
kind: Endpoints
metadata:
  name: external-service         #endpoint-name harus sama dengan service-name
  labels:
    label1: label
subsets:
  - addresses:
      - ip: 11.11.11.11
      - ip: 22.22.22.22
    ports:
      - port: 80
      