apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-job-name
  labels:
    label-key: label-value
  annotations:
    annotation-key1: annotation-value1
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      selector:
        matchLabels:
          abel-key1: label-value1
      template:
        metadata:
          name: pod-name
          labels:
            app: pod-la
        spec:
          restartPolicy: Never
          nodeSelector:
            hardisk: ssd             #syaratnya harus ada Node yang Label-nya hardisk=true
          containers:
            - name: container-name
              image: image-name
              ports:
                - containerPort: 80
