apiVersion: v1
kind: Pod
metadata:
  name: pod-name
spec:
  nodeSelector:
    gpu: "true"                            #syaratnya harus ada Node yang Label-nya gpu=true
  containers:
    - name: container-name
      image: image-name
      ports:
        - containerPort: 80
