apiVersion: v1
kind: Pod
metadata: 
  name: nginx-with-label                        #pod-name
  labels:
    team: finance                               #label-value1
    version: 1.4.5                              #label-value2
    environment: production                     #label-value3
    description: ini-adalah-aplikasi-nginx      #label-value4
spec:
  containers: 
    - name: nginx                               #container-name sama gak masalah, karena di running di Pod yang berbeda
      image: nginx                              #image-name
      ports:
        - containerPort: 80