##membuat pod
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nodejs-web                              #deployment-name
  labels:
    name: nodejs-web
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nodejs-web                          #pastikan matchLabels HARUS SAMA dengan label-template  
  template:
    metadata:
      name: nodejs-web                          #pod-name
      labels:
        name: nodejs-web                        #label-template (label pod) haru sama dengan matchLabels dan label service
    spec: 
      containers:
        - name: nodejs-web                      #container-name
          image: khannedy/nodejs-web:1          #image-name
          ports:
            - containerPort: 3000 